-- 0057_tag_alias.sql — tag aliases and canonical tag hub (SPEC-v2 27.9, P104).
-- An alias maps a non-canonical tag to its canonical form at write time and via 301
-- redirects. confirms counts distinct L2 super-groups backing a non-seeded alias;
-- an alias is live when seeded OR confirms >= 2. Additions come from a passed `alias`
-- proposal (platform scope, L2, 48 h) or two L2 confirmations; the janitor retags
-- existing rows forward only (alias -> canonical). Ecosystems never cross: an alias is
-- refused when it is itself a canonical tag or when it would re-point a known tag.

CREATE TABLE tag_alias (
  alias      text PRIMARY KEY CHECK (alias ~ '^[a-z0-9][a-z0-9._+-]{0,31}$'),
  tag        text NOT NULL   CHECK (tag   ~ '^[a-z0-9][a-z0-9._+-]{0,31}$'),
  confirms   int  NOT NULL DEFAULT 0,
  seeded     bool NOT NULL DEFAULT false,
  confirmers text[] NOT NULL DEFAULT '{}',
  created    timestamptz NOT NULL DEFAULT now(),
  CHECK (alias <> tag)
);
CREATE INDEX tag_alias_tag_idx ON tag_alias (tag);
-- live aliases (seeded or twice-confirmed) drive Canon and the forward retag.
CREATE INDEX tag_alias_live_idx ON tag_alias (alias) WHERE seeded OR confirms >= 2;

INSERT INTO tag_alias (alias, tag, seeded, confirms) VALUES
  ('ai', 'artificial-intelligence', true, 0),
  ('airflow', 'apache-airflow', true, 0),
  ('android-os', 'android', true, 0),
  ('angular2', 'angular', true, 0),
  ('ansbl', 'ansible', true, 0),
  ('apache-httpd', 'apache', true, 0),
  ('apache-kafka', 'kafka', true, 0),
  ('asp-net', 'aspnet-core', true, 0),
  ('aspnet', 'aspnet-core', true, 0),
  ('aws', 'amazon-web-services', true, 0),
  ('azure', 'microsoft-azure', true, 0),
  ('bash-shell', 'bash', true, 0),
  ('beautiful-soup', 'beautifulsoup', true, 0),
  ('bs4', 'beautifulsoup', true, 0),
  ('c-plus-plus', 'cpp', true, 0),
  ('c-sharp', 'csharp', true, 0),
  ('cd-deploy', 'continuous-deployment', true, 0),
  ('cf-cloud', 'cloudflare', true, 0),
  ('ci', 'continuous-integration', true, 0),
  ('cli', 'command-line-interface', true, 0),
  ('clj', 'clojure', true, 0),
  ('cockroach', 'cockroachdb', true, 0),
  ('cplusplus', 'cpp', true, 0),
  ('crdb', 'cockroachdb', true, 0),
  ('cs-lang', 'csharp', true, 0),
  ('css3', 'css', true, 0),
  ('cv2', 'opencv', true, 0),
  ('dart-lang', 'dart', true, 0),
  ('django-py', 'django', true, 0),
  ('do-cloud', 'digitalocean', true, 0),
  ('docker-ce', 'docker', true, 0),
  ('dockerd', 'docker', true, 0),
  ('dot-net', 'dotnet', true, 0),
  ('dotnet-core', 'dotnet', true, 0),
  ('dynamo', 'dynamodb', true, 0),
  ('ecmascript', 'javascript', true, 0),
  ('elastic', 'elasticsearch', true, 0),
  ('es-lint', 'eslint', true, 0),
  ('es-search', 'elasticsearch', true, 0),
  ('es2015', 'javascript', true, 0),
  ('es6', 'javascript', true, 0),
  ('exlang', 'elixir', true, 0),
  ('express-js', 'express', true, 0),
  ('expressjs', 'express', true, 0),
  ('f-sharp', 'fsharp', true, 0),
  ('fast-api', 'fastapi', true, 0),
  ('flask-py', 'flask', true, 0),
  ('flutter-dart', 'flutter', true, 0),
  ('gcp', 'google-cloud', true, 0),
  ('gh', 'github', true, 0),
  ('gl', 'gitlab', true, 0),
  ('gnu-linux', 'linux', true, 0),
  ('go', 'golang', true, 0),
  ('go-lang', 'golang', true, 0),
  ('google-cloud-platform', 'google-cloud', true, 0),
  ('gql', 'graphql', true, 0),
  ('grafana-oss', 'grafana', true, 0),
  ('helm-chart', 'helm', true, 0),
  ('hf-ml', 'huggingface', true, 0),
  ('hs-lang', 'haskell', true, 0),
  ('html5', 'html', true, 0),
  ('httpd', 'apache', true, 0),
  ('hugging-face', 'huggingface', true, 0),
  ('idea-ide', 'intellij-idea', true, 0),
  ('intellij', 'intellij-idea', true, 0),
  ('ipynb', 'jupyter', true, 0),
  ('java-script', 'javascript', true, 0),
  ('jenkins-ci', 'jenkins', true, 0),
  ('jlab', 'jupyterlab', true, 0),
  ('js', 'javascript', true, 0),
  ('jupyter-notebook', 'jupyter', true, 0),
  ('jwt', 'json-web-token', true, 0),
  ('k8', 'kubernetes', true, 0),
  ('k8s', 'kubernetes', true, 0),
  ('keras-ml', 'keras', true, 0),
  ('kotlin-lang', 'kotlin', true, 0),
  ('kt', 'kotlin', true, 0),
  ('kube', 'kubernetes', true, 0),
  ('laravel-php', 'laravel', true, 0),
  ('llm', 'large-language-model', true, 0),
  ('lua-lang', 'lua', true, 0),
  ('maria', 'mariadb', true, 0),
  ('md-lang', 'markdown', true, 0),
  ('memcache', 'memcached', true, 0),
  ('ml', 'machine-learning', true, 0),
  ('mongo', 'mongodb', true, 0),
  ('ms-sql', 'sqlserver', true, 0),
  ('mssql', 'sqlserver', true, 0),
  ('my-sql', 'mysql', true, 0),
  ('nest-js', 'nestjs', true, 0),
  ('net-core', 'dotnet', true, 0),
  ('next-js', 'nextjs', true, 0),
  ('nextdotjs', 'nextjs', true, 0),
  ('ngx', 'nginx', true, 0),
  ('node', 'nodejs', true, 0),
  ('node-js', 'nodejs', true, 0),
  ('np-py', 'numpy', true, 0),
  ('nuxt', 'nuxtjs', true, 0),
  ('nuxt-js', 'nuxtjs', true, 0),
  ('oauth', 'oauth2', true, 0),
  ('oauth-2', 'oauth2', true, 0),
  ('objc', 'objective-c', true, 0),
  ('objectivec', 'objective-c', true, 0),
  ('ocp', 'openshift', true, 0),
  ('oop', 'object-oriented-programming', true, 0),
  ('os-general', 'operating-system', true, 0),
  ('pd-py', 'pandas', true, 0),
  ('perl-lang', 'perl', true, 0),
  ('pg', 'postgres', true, 0),
  ('pgsql', 'postgres', true, 0),
  ('php-lang', 'php', true, 0),
  ('posh', 'powershell', true, 0),
  ('post-man', 'postman', true, 0),
  ('postgre', 'postgres', true, 0),
  ('postgresdb', 'postgres', true, 0),
  ('postgresql', 'postgres', true, 0),
  ('prom', 'prometheus', true, 0),
  ('proto3', 'protobuf', true, 0),
  ('protocol-buffers', 'protobuf', true, 0),
  ('psql', 'postgres', true, 0),
  ('pwa', 'progressive-web-app', true, 0),
  ('pwsh', 'powershell', true, 0),
  ('py', 'python', true, 0),
  ('py3', 'python', true, 0),
  ('pyspark', 'apache-spark', true, 0),
  ('python3', 'python', true, 0),
  ('r-language', 'r-lang', true, 0),
  ('rabbit', 'rabbitmq', true, 0),
  ('rabbit-mq', 'rabbitmq', true, 0),
  ('rb', 'ruby', true, 0),
  ('react-js', 'react', true, 0),
  ('reactjs', 'react', true, 0),
  ('reactnative', 'react-native', true, 0),
  ('redis-db', 'redis', true, 0),
  ('regex', 'regular-expression', true, 0),
  ('regexp', 'regular-expression', true, 0),
  ('rest-api', 'rest', true, 0),
  ('restful', 'rest', true, 0),
  ('rlang', 'r-lang', true, 0),
  ('rn-mobile', 'react-native', true, 0),
  ('ror', 'rails', true, 0),
  ('ruby-on-rails', 'rails', true, 0),
  ('rust-lang', 'rust', true, 0),
  ('rustlang', 'rust', true, 0),
  ('scala-lang', 'scala', true, 0),
  ('scikit', 'scikit-learn', true, 0),
  ('scss', 'sass', true, 0),
  ('sklearn', 'scikit-learn', true, 0),
  ('spark', 'apache-spark', true, 0),
  ('spring-boot-java', 'spring-boot', true, 0),
  ('springboot', 'spring-boot', true, 0),
  ('sqlite3', 'sqlite', true, 0),
  ('sse-web', 'server-sent-events', true, 0),
  ('svelte-js', 'svelte', true, 0),
  ('sveltejs', 'svelte', true, 0),
  ('swagger', 'openapi', true, 0),
  ('symphony', 'symfony', true, 0),
  ('system-d', 'systemd', true, 0),
  ('tailwind', 'tailwindcss', true, 0),
  ('tailwind-css', 'tailwindcss', true, 0),
  ('tensor-flow', 'tensorflow', true, 0),
  ('tf-terraform', 'terraform', true, 0),
  ('tfm', 'terraform', true, 0),
  ('torch', 'pytorch', true, 0),
  ('ts', 'typescript', true, 0),
  ('type-script', 'typescript', true, 0),
  ('ubuntu-linux', 'ubuntu', true, 0),
  ('vs-code', 'visual-studio-code', true, 0),
  ('vscode', 'visual-studio-code', true, 0),
  ('vue-js', 'vue', true, 0),
  ('vuejs', 'vue', true, 0),
  ('wasm', 'webassembly', true, 0),
  ('web-pack', 'webpack', true, 0),
  ('web-socket', 'websocket', true, 0),
  ('websockets', 'websocket', true, 0),
  ('yml', 'yaml', true, 0)
ON CONFLICT (alias) DO NOTHING;
