-- 19.5 / 27.6 Gym: self-evaluation tasks generated by portable-Go modules (internal/gym/mods),
-- published as gym-<kind> services under the system root. gym_tasks is the instance pool (the
-- janitor keeps 50 unserved rows per (kind, level)); gym_scores holds an Elo-like level + running
-- accuracy per (root, kind); gym_attempts is the one-attempt-per-instance / per-day rate ledger.
-- Prompts, answers, seeds and salts are never served: pages and replies carry numbers and hashes
-- only. answer/secret are stored server-side so the code and containment checkers (leak, cite,
-- regex) can grade a candidate; they are never included in any response, page, feed or export.
CREATE TABLE gym_tasks (
  id          text PRIMARY KEY,                  -- 'g…'
  kind        text NOT NULL,
  level       int  NOT NULL CHECK (level BETWEEN 1 AND 4),
  seed        bigint NOT NULL,
  prompt      text NOT NULL,
  answer      text NOT NULL DEFAULT '',          -- server-only, never served
  secret      text NOT NULL DEFAULT '',          -- leak: the planted credential, never served
  answer_hash bytea NOT NULL,                    -- sha256(norm(answer) || salt)
  salt        bytea NOT NULL,
  checker     text NOT NULL CHECK (checker IN ('exact', 'numeric', 'code')),
  served_to   text,                              -- root the instance was served to (NULL = unserved)
  served_at   timestamptz,
  solved      bool NOT NULL DEFAULT false,
  attempts    int  NOT NULL DEFAULT 0,
  created     timestamptz NOT NULL DEFAULT now()
);
-- Pool refill picks the oldest unserved rows per (kind, level); serving reads by (root, kind).
CREATE INDEX gym_tasks_pool_idx    ON gym_tasks (kind, level, created) WHERE served_to IS NULL;
CREATE INDEX gym_tasks_served_idx  ON gym_tasks (served_to, kind, served_at) WHERE served_to IS NOT NULL;
CREATE INDEX gym_tasks_created_idx ON gym_tasks (created);

-- One Elo-like skill row per (root, kind): level (default 1.0), running accuracy, counters.
CREATE TABLE gym_scores (
  root     text NOT NULL,
  kind     text NOT NULL,
  level    real NOT NULL DEFAULT 1,
  acc      real NOT NULL DEFAULT 0,
  attempts int  NOT NULL DEFAULT 0,
  solved   int  NOT NULL DEFAULT 0,
  updated  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (root, kind)
);
CREATE INDEX gym_scores_kind_idx ON gym_scores (kind, attempts DESC);

-- One row per attempt (one attempt per instance; 50/day per root): the daily rate ledger.
CREATE TABLE gym_attempts (
  id      bigserial PRIMARY KEY,
  task    text NOT NULL REFERENCES gym_tasks(id) ON DELETE CASCADE,
  root    text NOT NULL,
  kind    text NOT NULL,
  correct bool NOT NULL,
  created timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX gym_attempts_task_idx     ON gym_attempts (task);   -- one attempt per instance
CREATE INDEX        gym_attempts_root_day_idx ON gym_attempts (root, created);
