package know

// seedAliasList is the embedded top list of 13.4 (bare name -> key; npm, pypi, go, crates,
// docker), inserted as seeded aliases by Register. One `alias key` pair per line.
const seedAliasList = `
react npm:react
react-dom npm:react-dom
next npm:next
nextjs npm:next
vue npm:vue
nuxt npm:nuxt
svelte npm:svelte
sveltekit npm:@sveltejs/kit
angular npm:@angular/core
solid-js npm:solid-js
astro npm:astro
vite npm:vite
webpack npm:webpack
rollup npm:rollup
esbuild npm:esbuild
parcel npm:parcel
turbo npm:turbo
typescript npm:typescript
ts-node npm:ts-node
tsx npm:tsx
babel npm:@babel/core
eslint npm:eslint
prettier npm:prettier
biome npm:@biomejs/biome
jest npm:jest
vitest npm:vitest
mocha npm:mocha
chai npm:chai
cypress npm:cypress
playwright npm:playwright
puppeteer npm:puppeteer
storybook npm:storybook
express npm:express
fastify npm:fastify
koa npm:koa
hono npm:hono
nestjs npm:@nestjs/core
socket.io npm:socket.io
ws npm:ws
axios npm:axios
node-fetch npm:node-fetch
undici npm:undici
got npm:got
lodash npm:lodash
underscore npm:underscore
ramda npm:ramda
moment npm:moment
dayjs npm:dayjs
date-fns npm:date-fns
luxon npm:luxon
uuid npm:uuid
nanoid npm:nanoid
zod npm:zod
yup npm:yup
joi npm:joi
ajv npm:ajv
dotenv npm:dotenv
commander npm:commander
yargs npm:yargs
inquirer npm:inquirer
chalk npm:chalk
ora npm:ora
debug npm:debug
winston npm:winston
pino npm:pino
morgan npm:morgan
helmet npm:helmet
cors npm:cors
passport npm:passport
jsonwebtoken npm:jsonwebtoken
jose npm:jose
bcrypt npm:bcrypt
argon2 npm:argon2
prisma npm:prisma
drizzle-orm npm:drizzle-orm
typeorm npm:typeorm
sequelize npm:sequelize
knex npm:knex
mongoose npm:mongoose
pg npm:pg
postgres-js npm:postgres
mysql2 npm:mysql2
better-sqlite3 npm:better-sqlite3
ioredis npm:ioredis
redis npm:redis
bullmq npm:bullmq
graphql npm:graphql
apollo-server npm:@apollo/server
trpc npm:@trpc/server
react-query npm:@tanstack/react-query
tanstack-query npm:@tanstack/react-query
react-router npm:react-router
react-router-dom npm:react-router-dom
redux npm:redux
redux-toolkit npm:@reduxjs/toolkit
zustand npm:zustand
jotai npm:jotai
mobx npm:mobx
rxjs npm:rxjs
tailwindcss npm:tailwindcss
postcss npm:postcss
autoprefixer npm:autoprefixer
sass npm:sass
styled-components npm:styled-components
emotion npm:@emotion/react
mui npm:@mui/material
chakra-ui npm:@chakra-ui/react
antd npm:antd
bootstrap npm:bootstrap
three npm:three
d3 npm:d3
chart.js npm:chart.js
framer-motion npm:framer-motion
gsap npm:gsap
sharp npm:sharp
jimp npm:jimp
multer npm:multer
formidable npm:formidable
nodemailer npm:nodemailer
stripe npm:stripe
openai npm:openai
anthropic-sdk npm:@anthropic-ai/sdk
langchain npm:langchain
electron npm:electron
tauri npm:@tauri-apps/api
react-native npm:react-native
expo npm:expo
pnpm npm:pnpm
yarn npm:yarn
npm npm:npm
nodemon npm:nodemon
pm2 npm:pm2
husky npm:husky
lint-staged npm:lint-staged
semver npm:semver
glob npm:glob
minimatch npm:minimatch
rimraf npm:rimraf
fs-extra npm:fs-extra
chokidar npm:chokidar
yaml npm:yaml
js-yaml npm:js-yaml
marked npm:marked
markdown-it npm:markdown-it
cheerio npm:cheerio
jsdom npm:jsdom
dompurify npm:dompurify
handlebars npm:handlebars
ejs npm:ejs
pug npm:pug
mdx npm:@mdx-js/mdx
swr npm:swr
immer npm:immer
classnames npm:classnames
clsx npm:clsx
requests pypi:requests
httpx pypi:httpx
aiohttp pypi:aiohttp
urllib3 pypi:urllib3
flask pypi:flask
django pypi:django
fastapi pypi:fastapi
starlette pypi:starlette
uvicorn pypi:uvicorn
gunicorn pypi:gunicorn
pydantic pypi:pydantic
pydantic-settings pypi:pydantic-settings
sqlalchemy pypi:sqlalchemy
alembic pypi:alembic
psycopg2 pypi:psycopg2
psycopg2-binary pypi:psycopg2-binary
psycopg pypi:psycopg
asyncpg pypi:asyncpg
pymongo pypi:pymongo
redis-py pypi:redis
celery pypi:celery
numpy pypi:numpy
pandas pypi:pandas
polars pypi:polars
scipy pypi:scipy
matplotlib pypi:matplotlib
seaborn pypi:seaborn
plotly pypi:plotly
scikit-learn pypi:scikit-learn
sklearn pypi:scikit-learn
torch pypi:torch
pytorch pypi:torch
tensorflow pypi:tensorflow
keras pypi:keras
jax pypi:jax
transformers pypi:transformers
datasets pypi:datasets
tokenizers pypi:tokenizers
accelerate pypi:accelerate
huggingface-hub pypi:huggingface-hub
langchain-py pypi:langchain
llama-index pypi:llama-index
openai-py pypi:openai
anthropic pypi:anthropic
pillow pypi:pillow
opencv-python pypi:opencv-python
pytest pypi:pytest
pytest-asyncio pypi:pytest-asyncio
tox pypi:tox
nox pypi:nox
mypy pypi:mypy
ruff pypi:ruff
black pypi:black
isort pypi:isort
flake8 pypi:flake8
pylint pypi:pylint
pre-commit pypi:pre-commit
poetry pypi:poetry
pip pypi:pip
setuptools pypi:setuptools
wheel pypi:wheel
hatch pypi:hatch
uv pypi:uv
pipx pypi:pipx
virtualenv pypi:virtualenv
click pypi:click
typer pypi:typer
rich pypi:rich
tqdm pypi:tqdm
loguru pypi:loguru
structlog pypi:structlog
python-dotenv pypi:python-dotenv
pyyaml pypi:pyyaml
toml pypi:toml
tomli pypi:tomli
jinja2 pypi:jinja2
markupsafe pypi:markupsafe
beautifulsoup4 pypi:beautifulsoup4
bs4 pypi:beautifulsoup4
lxml pypi:lxml
scrapy pypi:scrapy
selenium pypi:selenium
playwright-py pypi:playwright
boto3 pypi:boto3
botocore pypi:botocore
google-cloud-storage pypi:google-cloud-storage
azure-identity pypi:azure-identity
cryptography pypi:cryptography
pyjwt pypi:pyjwt
passlib pypi:passlib
bcrypt-py pypi:bcrypt
paramiko pypi:paramiko
fabric pypi:fabric
ansible pypi:ansible
docker-py pypi:docker
kubernetes-py pypi:kubernetes
grpcio pypi:grpcio
protobuf pypi:protobuf
websockets pypi:websockets
python-multipart pypi:python-multipart
orjson pypi:orjson
ujson pypi:ujson
msgpack pypi:msgpack
attrs pypi:attrs
cattrs pypi:cattrs
marshmallow pypi:marshmallow
dataclasses-json pypi:dataclasses-json
arrow pypi:arrow
pendulum pypi:pendulum
python-dateutil pypi:python-dateutil
pytz pypi:pytz
networkx pypi:networkx
sympy pypi:sympy
statsmodels pypi:statsmodels
xgboost pypi:xgboost
lightgbm pypi:lightgbm
jupyter pypi:jupyter
ipython pypi:ipython
notebook pypi:notebook
streamlit pypi:streamlit
gradio pypi:gradio
dash pypi:dash
sphinx pypi:sphinx
mkdocs pypi:mkdocs
twine pypi:twine
pgx go:github.com/jackc/pgx/v5
pq go:github.com/lib/pq
gorm go:gorm.io/gorm
sqlx go:github.com/jmoiron/sqlx
go-redis go:github.com/redis/go-redis/v9
gin go:github.com/gin-gonic/gin
echo go:github.com/labstack/echo/v4
fiber go:github.com/gofiber/fiber/v2
chi go:github.com/go-chi/chi/v5
gorilla-mux go:github.com/gorilla/mux
gorilla-websocket go:github.com/gorilla/websocket
cobra go:github.com/spf13/cobra
viper go:github.com/spf13/viper
pflag go:github.com/spf13/pflag
zap go:go.uber.org/zap
zerolog go:github.com/rs/zerolog
logrus go:github.com/sirupsen/logrus
testify go:github.com/stretchr/testify
gomock go:go.uber.org/mock
grpc-go go:google.golang.org/grpc
protobuf-go go:google.golang.org/protobuf
golang-x-net go:golang.org/x/net
golang-x-sync go:golang.org/x/sync
golang-x-crypto go:golang.org/x/crypto
golang-x-text go:golang.org/x/text
golang-x-sys go:golang.org/x/sys
golang-x-oauth2 go:golang.org/x/oauth2
golang-x-tools go:golang.org/x/tools
golang-jwt go:github.com/golang-jwt/jwt/v5
google-uuid go:github.com/google/uuid
go-cmp go:github.com/google/go-cmp
errgroup go:golang.org/x/sync
aws-sdk-go-v2 go:github.com/aws/aws-sdk-go-v2
docker-client-go go:github.com/docker/docker
client-go go:k8s.io/client-go
controller-runtime go:sigs.k8s.io/controller-runtime
prometheus-client-golang go:github.com/prometheus/client_golang
opentelemetry-go go:go.opentelemetry.io/otel
wazero go:github.com/tetratelabs/wazero
bbolt go:go.etcd.io/bbolt
badger go:github.com/dgraph-io/badger/v4
sqlite-go go:modernc.org/sqlite
go-sqlite3 go:github.com/mattn/go-sqlite3
yaml-go go:gopkg.in/yaml.v3
toml-go go:github.com/BurntSushi/toml
mapstructure go:github.com/mitchellh/mapstructure
validator-go go:github.com/go-playground/validator/v10
templ go:github.com/a-h/templ
serde crates:serde
serde_json crates:serde_json
tokio crates:tokio
async-std crates:async-std
hyper crates:hyper
reqwest crates:reqwest
axum crates:axum
actix-web crates:actix-web
rocket crates:rocket
warp crates:warp
tower crates:tower
tonic crates:tonic
prost crates:prost
clap crates:clap
anyhow crates:anyhow
thiserror crates:thiserror
eyre crates:eyre
tracing crates:tracing
log crates:log
env_logger crates:env_logger
rand crates:rand
regex crates:regex
chrono crates:chrono
time-rs crates:time
uuid-rs crates:uuid
sqlx-rs crates:sqlx
diesel crates:diesel
sea-orm crates:sea-orm
rusqlite crates:rusqlite
rayon crates:rayon
crossbeam crates:crossbeam
parking_lot crates:parking_lot
itertools crates:itertools
bytes crates:bytes
futures crates:futures
syn crates:syn
quote crates:quote
proc-macro2 crates:proc-macro2
wasm-bindgen crates:wasm-bindgen
bevy crates:bevy
tauri-rs crates:tauri
polars-rs crates:polars
ndarray crates:ndarray
image-rs crates:image
ring crates:ring
rustls crates:rustls
openssl-rs crates:openssl
toml-rs crates:toml
hashbrown crates:hashbrown
postgres docker:postgres
mysql docker:mysql
mariadb docker:mariadb
mongo docker:mongo
redis-image docker:redis
valkey docker:valkey
nginx docker:nginx
traefik docker:traefik
caddy docker:caddy
haproxy docker:haproxy
node docker:node
python docker:python
golang docker:golang
rust docker:rust
alpine docker:alpine
debian docker:debian
ubuntu docker:ubuntu
busybox docker:busybox
rabbitmq docker:rabbitmq
kafka docker:apache/kafka
elasticsearch docker:elasticsearch
opensearch docker:opensearchproject/opensearch
grafana docker:grafana/grafana
prometheus docker:prom/prometheus
loki docker:grafana/loki
minio docker:minio/minio
vault docker:hashicorp/vault
consul docker:hashicorp/consul
keycloak docker:quay.io/keycloak/keycloak
gitea docker:gitea/gitea
forgejo docker:codeberg.org/forgejo/forgejo
nextcloud docker:nextcloud
wordpress docker:wordpress
memcached docker:memcached
httpd docker:httpd
tomcat docker:tomcat
eclipse-temurin docker:eclipse-temurin
clickhouse docker:clickhouse/clickhouse-server
`
