package legal

// openAPI is the OpenAPI fragment merged into /openapi.json for the recipient-reveal report endpoint
// and the operator review surface (8.3, 8.6).
const openAPI = `{"paths":{
"/v1/x/report":{"post":{"operationId":"xReport","tags":["e2e"],"summary":"Recipient-reveal report (SECURITY-E2EE 8.3 / SPEC-v2 26.3): disclose one sealed message's franking key and decrypted (type,payload); the server verifies the commitment, runs normalise->scrub->lexicon->hazard in memory and stores only the verdict (kinds,score,sha256) and the signatures, never the text. kind bad-frank flags an unfrankable envelope. X-Cx-Sig required; recipient only.","requestBody":{"required":true,"content":{"application/json":{"schema":{"type":"object","required":["seq"],"properties":{"kind":{"type":"string","enum":["frank","bad-frank"],"default":"frank"},"seq":{"type":"integer","description":"the reported envelope's sequence in your inbox"},"kf":{"type":"string","description":"base64url 32-byte franking key (kind frank)"},"type":{"type":"integer","description":"inner message type (kind frank)"},"payload":{"type":"string","description":"base64url decrypted plaintext (kind frank)"},"why":{"type":"string","maxLength":200}}}}}},"responses":{"200":{"description":"ok verified | ok verified upheld | ok flagged unfrankable"},"400":{"description":"err bad frank (disclosure mismatch; report_trust halved)"},"401":{"description":"err sig"},"403":{"description":"err auth (not the recipient)"},"404":{"description":"err notfound (message expired or never yours)"},"429":{"description":"err quota (bad-frank cap)"}}}},
"/admin/x/queue":{"get":{"operationId":"xQueue","tags":["ops"],"summary":"Open recipient-report review queue with evidence verdicts (ops token); no plaintext","parameters":[{"name":"since","in":"query","schema":{"type":"string","format":"date-time"}}],"responses":{"200":{"description":"queue lines and JSON"},"401":{"description":"err auth"}}}},
"/admin/x/decide":{"post":{"operationId":"xDecide","tags":["ops"],"summary":"Decide a review item (ops token): purge deletes the ciphertext by locator, freeze freezes the sender root, dismiss closes it","requestBody":{"required":true,"content":{"application/json":{"schema":{"type":"object","required":["id","action"],"properties":{"id":{"type":"integer"},"action":{"type":"string","enum":["purge","freeze","dismiss"]},"note":{"type":"string","maxLength":300}}}}}},"responses":{"200":{"description":"ok decided <action>"},"401":{"description":"err auth"},"404":{"description":"err notfound"},"409":{"description":"err decided"}}}}
}}`
